#
# Configuration file for n3fit
#
description: NNPDF4.0 NLO global, alphas=0.118

############################################################
# frac: training fraction
# ewk: apply ewk k-factors
# sys: systematics treatment (see systypes)
#

NLODatasets: &NLODatasets
- {dataset: NMCPD_dw_ite, frac: 0.75}
- {dataset: NMC, frac: 0.75, cfac: ["Y"]}
- {dataset: SLACP_dwsh, frac: 0.75}
- {dataset: SLACD_dw_ite, frac: 0.75}
- {dataset: BCDMSP_dwsh, frac: 0.75}
- {dataset: BCDMSD_dw_ite, frac: 0.75}
- {dataset: CHORUSNUPb_dw_ite, frac: 0.75}
- {dataset: CHORUSNBPb_dw_ite, frac: 0.75}
- {dataset: NTVNUDMNFe_dw_ite, frac: 0.75, cfac: []}
- {dataset: NTVNBDMNFe_dw_ite, frac: 0.75, cfac: []}
- {dataset: HERACOMBNCEM, frac: 0.75, cfac: ["Y"]}
- {dataset: HERACOMBNCEP460, frac: 0.75, cfac: ["Y"]}
- {dataset: HERACOMBNCEP575, frac: 0.75, cfac: ["Y"]}
- {dataset: HERACOMBNCEP820, frac: 0.75, cfac: ["Y"]}
- {dataset: HERACOMBNCEP920, frac: 0.75, cfac: ["Y"]}
- {dataset: HERACOMBCCEM, frac: 0.75}
- {dataset: HERACOMBCCEP, frac: 0.75}
- {dataset: HERACOMB_SIGMARED_C, frac: 0.75}
- {dataset: HERACOMB_SIGMARED_B, frac: 0.75}
- {dataset: DYE886R_dw_ite, frac: 0.75}
- {dataset: DYE886P, frac: 0.75, cfac: []}
- {dataset: DYE605_dw_ite, frac: 0.75, cfac: []}
- {dataset: DYE906R_dw_ite, frac: 0.75, cfac: [ACC]}
- {dataset: CDFZRAP_NEW, frac: 0.75, cfac: []}
- {dataset: D0ZRAP_40, frac: 0.75, cfac: []}
- {dataset: D0WMASY, frac: 0.75, cfac: []}
- {dataset: ATLASWZRAP36PB, frac: 0.75, cfac: []}
- {dataset: ATLASZHIGHMASS49FB, frac: 0.75, cfac: ["Y"]}
- {dataset: ATLASLOMASSDY11EXT, frac: 0.75, cfac: []}
- {dataset: ATLASWZRAP11CC, frac: 0.75, cfac: []}
- {dataset: ATLASWZRAP11CF, frac: 0.75, cfac: []}
- {dataset: ATLASDY2D8TEV, frac: 0.75, cfac: ["Y"]}
- {dataset: ATLAS_DY_2D_8TEV_LOWMASS, frac: 0.75, cfac: []}
- {dataset: ATLAS_WZ_TOT_13TEV, frac: 0.75, cfac: [NRM]}
- {dataset: ATLAS_WP_JET_8TEV_PT, frac: 0.75, cfac: []}
- {dataset: ATLAS_WM_JET_8TEV_PT, frac: 0.75, cfac: []}
- {dataset: ATLAS_WCHARM_WP_DIFF_7TEV, frac: 0.75, cfac: []}
- {dataset: ATLAS_WCHARM_WM_DIFF_7TEV, frac: 0.75, cfac: []}
- {dataset: ATLASZPT8TEVMDIST, frac: 0.75, cfac: []}
- {dataset: ATLASZPT8TEVYDIST, frac: 0.75, cfac: []}
- {dataset: ATLASTTBARTOT7TEV, frac: 0.75, cfac: []}
- {dataset: ATLASTTBARTOT8TEV, frac: 0.75, cfac: []}
- {dataset: ATLAS_TTBARTOT_13TEV_FULLLUMI, frac: 0.75, cfac: []}
- {dataset: ATLAS_TTB_DIFF_8TEV_LJ_TRAPNORM, frac: 0.75, cfac: []}
- {dataset: ATLAS_TTB_DIFF_8TEV_LJ_TTRAPNORM, frac: 0.75, cfac: []}
- {dataset: ATLAS_TOPDIFF_DILEPT_8TEV_TTRAPNORM, frac: 0.75, cfac: []}
- {dataset: ATLAS_1JET_8TEV_R06_DEC, frac: 0.75, cfac: []}
- {dataset: ATLAS_2JET_7TEV_R06, frac: 0.75, cfac: []}
- {dataset: ATLASPHT15_SF, frac: 0.75, cfac: [EWK]}
- {dataset: ATLAS_SINGLETOP_TCH_R_7TEV, frac: 0.75, cfac: []}
- {dataset: ATLAS_SINGLETOP_TCH_R_13TEV, frac: 0.75, cfac: []}
- {dataset: ATLAS_SINGLETOP_TCH_DIFF_7TEV_T_RAP_NORM, frac: 0.75, cfac: []}
- {dataset: ATLAS_SINGLETOP_TCH_DIFF_7TEV_TBAR_RAP_NORM, frac: 0.75, cfac: []}
- {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_T_RAP_NORM, frac: 0.75, cfac: []}
- {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_TBAR_RAP_NORM, frac: 0.75, cfac: []}
- {dataset: CMSWEASY840PB, frac: 0.75, cfac: []}
- {dataset: CMSWMASY47FB, frac: 0.75, cfac: []}
- {dataset: CMSDY2D11, frac: 0.75, cfac: ["Y"]}
- {dataset: CMSWMU8TEV, frac: 0.75, cfac: []}
- {dataset: CMSZDIFF12, frac: 0.75, cfac: [NRM]}
- {dataset: CMS_2JET_7TEV, frac: 0.75, cfac: []}
- {dataset: CMS_1JET_8TEV, frac: 0.75, cfac: []}
- {dataset: CMSTTBARTOT7TEV, frac: 0.75, cfac: []}
- {dataset: CMSTTBARTOT8TEV, frac: 0.75, cfac: []}
- {dataset: CMSTTBARTOT13TEV, frac: 0.75, cfac: []}
- {dataset: CMSTOPDIFF8TEVTTRAPNORM, frac: 0.75, cfac: []}
- {dataset: CMSTTBARTOT5TEV, frac: 0.75, cfac: []}
- {dataset: CMS_TTBAR_2D_DIFF_MTT_TRAP_NORM, frac: 0.75, cfac: []}
- {dataset: CMS_TTB_DIFF_13TEV_2016_2L_TRAP, frac: 0.75, cfac: []}
- {dataset: CMS_TTB_DIFF_13TEV_2016_LJ_TRAP, frac: 0.75, cfac: []}
- {dataset: CMS_SINGLETOP_TCH_TOT_7TEV, frac: 0.75, cfac: []}
- {dataset: CMS_SINGLETOP_TCH_R_8TEV, frac: 0.75, cfac: []}
- {dataset: CMS_SINGLETOP_TCH_R_13TEV, frac: 0.75, cfac: []}
- {dataset: CMSWCHARMTOT, frac: 0.75}
- {dataset: CMSWCHARMRAT, frac: 0.75}
- {dataset: CMS_WCHARM_DIFF_UNNORM_13TEV, frac: 0.75}
- {dataset: LHCBZ940PB, frac: 0.75, cfac: []}
- {dataset: LHCBZEE2FB_40, frac: 0.75, cfac: []}
- {dataset: LHCBWZMU7TEV, frac: 0.75, cfac: [NRM]}
- {dataset: LHCBWZMU8TEV, frac: 0.75, cfac: [NRM]}
- {dataset: LHCB_Z_13TEV_DIMUON, frac: 0.75, cfac: []}
- {dataset: LHCB_Z_13TEV_DIELECTRON, frac: 0.75, cfac: []}
- {dataset: CMSDY1D12, frac: 0.75, cfac: ["Y"]}
- {dataset: CMS_HMDY_13TEV, frac: 0.75, cfac: ["Y"]}

dataset_inputs: *NLODatasets

write_cfactors_data:
  - {name: "Y", new_value: 0.1, default_value: -0.001, quad_on: False}

output_name: Y0p1

############################################################
datacuts:
  t0pdfset: 210712-theory-001   # PDF set to generate t0 covmat
  q2min: 3.49                        # Q2 minimum
  w2min: 12.5                        # W2 minimum
  use_cuts: internal


############################################################
theory:
  theoryid: 208     # database id

############################################################
trvlseed: 376191634
nnseed: 2080989803
mcseed: 75955222
save: false
genrep: true      # true = generate MC replicas, false = use real data

parameters: # This defines the parameter dictionary that is passed to the Model Trainer
  nodes_per_layer: [25, 20, 8]
  activation_per_layer: [tanh, tanh, linear]
  initializer: glorot_normal
  optimizer:
    clipnorm: 6.073e-6
    learning_rate: 2.621e-3
    optimizer_name: Nadam
  epochs: 17000
  positivity:
    initial: 184.8
    multiplier:
  integrability:
    initial: 10
    multiplier:
  stopping_patience: 0.1
  layer_type: dense
  dropout: 0.0
  threshold_chi2: 3.5

fitting:
  fitbasis: EVOL  # EVOL (7), EVOLQED (8), etc.
  basis:
  - {fl: sng, trainable: false, smallx: [1.121, 1.154], largex: [1.498, 3.138]}
  - {fl: g, trainable: false, smallx: [0.9224, 1.149], largex: [3.266, 6.214]}
  - {fl: v, trainable: false, smallx: [0.5279, 0.8017], largex: [1.6, 3.588]}
  - {fl: v3, trainable: false, smallx: [0.2011, 0.4374], largex: [1.761, 3.427]}
  - {fl: v8, trainable: false, smallx: [0.5775, 0.8357], largex: [1.589, 3.378]}
  - {fl: t3, trainable: false, smallx: [-0.484, 1.0], largex: [1.763, 3.397]}
  - {fl: t8, trainable: false, smallx: [0.6714, 0.9197], largex: [1.572, 3.496]}
  - {fl: t15, trainable: false, smallx: [1.073, 1.164], largex: [1.503, 3.636]}

############################################################
positivity:
  posdatasets:
  - {dataset: POSF2U, maxlambda: 1e6}        # Positivity Lagrange Multiplier
  - {dataset: POSF2DW, maxlambda: 1e6}
  - {dataset: POSF2S, maxlambda: 1e6}
  - {dataset: POSFLL, maxlambda: 1e6}
  - {dataset: POSDYU, maxlambda: 1e10}
  - {dataset: POSDYD, maxlambda: 1e10}
  - {dataset: POSDYS, maxlambda: 1e10}
  - {dataset: POSF2C, maxlambda: 1e6}
  - {dataset: POSXUQ, maxlambda: 1e6}        # Positivity of MSbar PDFs
  - {dataset: POSXUB, maxlambda: 1e6}
  - {dataset: POSXDQ, maxlambda: 1e6}
  - {dataset: POSXDB, maxlambda: 1e6}
  - {dataset: POSXSQ, maxlambda: 1e6}
  - {dataset: POSXSB, maxlambda: 1e6}
  - {dataset: POSXGL, maxlambda: 1e6}

############################################################
integrability:
  integdatasets:
  - {dataset: INTEGXT8, maxlambda: 1e2}
  - {dataset: INTEGXT3, maxlambda: 1e2}

closuretest:
  filterseed: 0 # Random seed to be used in filtering data partitions
  fakedata: true     # true = to use FAKEPDF to generate pseudo-data
  fakepdf: NNPDF40_nlo_as_01180      # Theory input for pseudo-data
  errorsize: 1.0    # uncertainties rescaling
  fakenoise: true    # true = to add random fluctuations to pseudo-data
  rancutprob: 1.0   # Fraction of data to be included in the fit
  rancutmethod: 0   # Method to select rancutprob data fraction
  rancuttrnval: false # 0(1) to output training(valiation) chi2 in report
  printpdf4gen: false # To print info on PDFs during minimization

seed: 0
rngalgo: 0
############################################################
debug: false
maxcores: 4

actions_:
  - write_cfactor_files
  - write_runcard
  - launch_vpsetupfit
  - launch_vprebuilddata
  - write_sm_runcard
